Kubernetes 2
Otus-DevOps-2017-11/etozhecyber_microservices pull request #13
Opened 2018-04-03 19:48 UTC by etozhecyber

Все yml файлы в папке kubernetes. Скриншот с рабочим приложением https://pasteboard.co/HeWIl2d.png

2018-04-22 08:31 UTC, vitkhab requested changes
В целом, задание выполнено. Приложение запускается с небольшими правками.

Есть небольшие недочеты которые нужно исправить для успешного зачета ДЗ:
- исправить `NodePort` в описании сервиса `ui`
- исправить количество реплик для деплойментов приложения
- подмерджить `master`-ветку в ветку `kubernetes-2`, для удобства чтения

Дополнительный вопрос. Как ты справлялся с проблемой, когда приложение не запускается без запущенного зипкина?

2018-04-22 08:31 UTC, vitkhab commented on kubernetes/ui-service.yml
> +  - NodePort: 32092
Опечатка. Нужно `nodePort` с маленькой буквы

2018-04-22 08:31 UTC, vitkhab commented on kubernetes/post-deployment.yml
> +  replicas: 1
По заданию требовалось сделать 3 реплики

2018-04-22 08:31 UTC, vitkhab commented on kubernetes/ui-deployment.yml
> +  replicas: 1
По заданию требовалось сделать 3 реплики

2018-04-22 08:31 UTC, vitkhab commented on kubernetes/comment-deployment.yml
> +  replicas: 1
По заданию требовалось сделать 3 реплики

2018-04-22 08:32 UTC, vitkhab commented
Сделав больше реплик, ты смог бы наблюдать на своей инсталяции, что некоторые запросы приходят на разные контейнеры и таким образом реализуется балансировка.

В интерфейсе приложения это выглядит так:
<img width="508" alt="screen shot 2018-04-22 at 11 29 07" src="https://user-images.githubusercontent.com/12728509/39092995-ad69e936-4620-11e8-81d7-2e5334bea10a.png">
<img width="492" alt="screen shot 2018-04-22 at 11 28 38" src="https://user-images.githubusercontent.com/12728509/39092996-ad857732-4620-11e8-90b1-a827d4617b7c.png">

2018-04-22 19:39 UTC, etozhecyber commented on kubernetes/ui-service.yml
> +  - NodePort: 32092
А вы в этом уверены? Везде в документациях с большой.

И вот по быстрому загуглил:
https://github.com/kubernetes/ingress-nginx/blob/master/deploy/provider/baremetal/service-nodeport.yaml

2018-04-22 19:41 UTC, etozhecyber commented on kubernetes/post-deployment.yml
> +  replicas: 1
У меня c minikube под virtual box'ом тормозил жутко. Я использую 4х гиговый macbook air :( Забыл вернуть все в зад :(

2018-04-22 20:04 UTC, etozhecyber commented
По поводу зипкина - собрал предыдущую версию как советовали в чатике

2018-04-22 20:06 UTC, etozhecyber commented
Я наблюдал эти несколько реплик, но во время этого у меня комп очень тормозил. minikube на macbook air с 4 гигами оперативки очень сильно систему грузит. Я тогда реплики преуменьшил и забыл вернуть

2018-04-23 16:35 UTC, vitkhab approved these changes
Спасибо за внесенные изменения! Можно мерджить

2018-04-24 19:08 UTC, merged