add docker-compose
Otus-DevOps-2017-11/etozhecyber_microservices pull request #5
Opened 2018-02-13 16:40 UTC by etozhecyber

Добавил docker-compose.yml

2018-02-14 10:18 UTC, serjs requested changes

2018-02-14 10:18 UTC, serjs commented on reddit-microservices/docker-compose.yml
> +    image: ${REGISTRY_USERNAME}/ui:${UIVERSION}
Привет! Переменные вида UIVERSION лучше разделять символом нижнего подчеркивания, к примеру. Совсем нечитаемая штука выходит. Пример: UI_VERSION или UI_VER

2018-02-18 16:06 UTC, etozhecyber commented
Готово, переименовал переменные!

2018-02-24 13:54 UTC, etozhecyber commented
@serjs глянь исправил все, посмотри пожалста

2018-02-24 13:55 UTC, merged