Homework-21 Monitoring 1
Otus-DevOps-2017-11/etozhecyber_microservices pull request #8
Opened 2018-02-25 20:17 UTC by etozhecyber

Мой dockerhub https://hub.docker.com/u/cyberdude/

2018-03-02 17:01 UTC, etozhecyber commented
ping :) @postgred @Nklya

2018-03-03 17:23 UTC, Nklya requested changes
Добрый вечер.

Андрей, есть несколько проблем:
1. Почему в диффе нет собственно папки `monitoring/prometheus`?
2. Почему не удалена `reddit-microservices`

Проверяй пожалуйста, что коммитишь и итоговый результат.
Повторное ревью после фиксов

2018-03-03 17:23 UTC, Nklya commented on docker-monolith/docker-1.log
> -REPOSITORY                    TAG                 IMAGE ID            CREATED             SIZE
Почему этот файл удаляется?

2018-03-03 17:23 UTC, Nklya commented on .gitignore
>  prometheus/
Эта запись здесь зачем?

2018-03-03 17:23 UTC, Nklya commented on docker/.env.example
> +UI_VERSION=1.0
И эти версии точно работают сейчас?

2018-03-11 13:05 UTC, etozhecyber commented on .gitignore
>  prometheus/
это я объединил 3 .gitignore файла, наверно зря

2018-03-11 13:26 UTC, etozhecyber commented
Пофиксил

2018-03-11 13:34 UTC, Nklya approved these changes
Сейчас более-менее ок, build_info.txt зачем удален???
Его нужно вернуть и вычистить то, что попало.

2018-03-11 13:34 UTC, Nklya commented on src/ui/build_info.txt
> +41c231d
Надо вычистить и в .gitignore

2018-03-11 13:34 UTC, Nklya commented on src/post-py/build_info.txt
> +41c231d
Надо вычистить и в .gitignore

2018-03-11 13:34 UTC, Nklya commented on src/comment/build_info.txt
> +41c231d
Надо вычистить и в .gitignore

2018-03-11 13:34 UTC, Nklya commented on .gitignore
> -build_info.txt
build_info.txt зачем удалено?

2018-03-11 14:18 UTC, merged