homework-23
Otus-DevOps-2017-11/etozhecyber_microservices pull request #9
Opened 2018-03-19 19:18 UTC by etozhecyber

Добавил Graphana и alertmanager

2018-03-21 06:59 UTC, Nklya requested changes
Добрый день.

Андрей, все выглядит относительно нормально.

Нужно исправить проблему с тем, что все, что относится к мониторингу, должно быть вынесено из docker-compose.yml в docker-compose-monitoring.yml

2018-03-21 06:59 UTC, Nklya commented on docker/docker-compose.yml
> +  alertmanager:
Все, что относится к мониторингу, должно быть вынесено из docker-compose.yml в docker-compose-monitoring.yml

2018-03-25 13:57 UTC, etozhecyber commented
Все исправил!

2018-03-25 14:26 UTC, Nklya approved these changes
Да, теперь ок 👍

2018-03-26 13:22 UTC, merged